using DiSourceGenerator.Helpers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DiSourceGenerator.Generators;

/// <auto-generated />
[Generator]
public class ServiceCollectionGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var serviceCollectionsToGenerate = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                SourceGeneratorPackagedObjects.Namespaces.AutoDiRegistrationAttributes + "." + SourceGeneratorPackagedObjects.ClassNames.GeneratedServiceCollectionAttribute,
                // Only static partial classes
                (node, _) => NodeIsPartialClass(node),
                static (context, _) =>
                {
                    // The symbol gives us easy access to the namespace and name
                    var symbol = (INamedTypeSymbol)context.TargetSymbol;

                    return new ClassModel(
                        symbol.Name,
                        symbol.ContainingNamespace.ToDisplayString()
                    );
                });

        context.RegisterSourceOutput(serviceCollectionsToGenerate, GenerateServiceCollections);
    }

    private static bool NodeIsPartialClass(SyntaxNode node) =>
        node is ClassDeclarationSyntax classDeclaration && classDeclaration.Modifiers.Any(SyntaxKind.PartialKeyword);

    private static void GenerateServiceCollections(SourceProductionContext productionContext, ClassModel model)
    {
        var source = GeneratedObjectTemplates.GeneratedServiceCollection(model.Name, model.Namespace);

        productionContext.AddSource($"{model.Name}.g.cs", source);
    }
}

public record struct ClassModel(
    string Name,
    string Namespace
);